version: "3.9"
services:
  neo4j:
    image: neo4j:latest
    container_name: greek-neo4j
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - $HOME/neo4j/data:/data
    ports:
      - "7474:7474"
      - "7687:7687"
