const {
  NEO4J_USERNAME = '',
  NEO4J_PASSWORD = '',
  NEO4J_INSTANCE_ID = '',
  NEO4J_INSTANCE_NAME = '',
  ENV,
  GA_TRACKING_ID,
} = process.env;

export {
  NEO4J_USERNAME,
  NEO4J_PASSWORD,
  NEO4J_INSTANCE_ID,
  NEO4J_INSTANCE_NAME,
  ENV,
  GA_TRACKING_ID,
}
